//144 × 256
pub const ORIGINAL_WIDTH: f32 = 144.;
pub const ORIGINAL_HEIGHT: f32 = 256.;

pub const TWEEN_CALLBACK_MASK_CENTER_BACK: u64 = 1;
pub const TWEEN_CALLBACK_MENU_TO_GAME: u64 = 2;
pub const TWEEN_CALLBACK_DEATH_WHITE: u64 = 3;
pub const TWEEN_CALLBACK_GAME_TO_MENU: u64 = 4;
pub const TWEEN_CALLBACK_PANEL_UP: u64 = 5;
